apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/digital_wallet_db"
  SPRING_REDIS_HOST: "redis-service"
  SPRING_REDIS_PORT: "6379"
  SPRING_CLOUD_AWS_ENDPOINT: "http://localstack-service:4566"
  SPRING_MAIL_HOST: "mailhog-service"
  SPRING_MAIL_PORT: "1025"
  JWT_EXPIRATION: "86400000"
