apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Base64 encoded values
  # postgres
  SPRING_DATASOURCE_PASSWORD: "MTIzNA==" # 1234
  # jwt-secret (c2VjdXJpdHktandrLXNlY3JldC1rZXktZm9yLWhzMjU2LXNpZ25pbmc=)
  JWT_SECRET: "YzJWamRYSnBkSGt0YW5kckxYTmxZM0psZEMxclpYNHRabTlyTFdoc01qVTJMWE5wWjI1cGJuZz0="
  # aws dummy
  SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY: "dGVzdA==" # test
  SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY: "dGVzdA==" # test
